### ISSUE TITLE
Teleport on the touchpad is confusing

### ISSUE THREAD

**Issue by dmarcos** [aframevr/a-painter#177] opened 2016-12-24 21:45 UTC
The thouchpad is also used to change the brush size causing a lot unintentional teleportations. I'm testing this Christmas with people that had never used a-painter or VR.

**Comment by feiss** [comment] 2016-12-25 00:08
Yes, it may be confusing for newbies, in the same way that they often use the thumbnail for painting or selecting instead of using the trigger. 

Not sure about the best way to deal with this. Maybe enabling the teleport only on the controller with the menu opened, maybe disabling the size control in the touchpad..

Mm I think the best option, since it is not a very used feature, would be to put a "teleport" button in the menu.

**Comment by machenmusik** [comment] 2016-12-25 00:26
the approach I took with fork of @fernandojsg 's teleport control (not with A-Painter though) was to use A-Frame `hand-controls` and map to gestures like `pointing` -- although on Vive, because the grip button is hard to press and therefore isn't required to point, that might not help.  For Oculus Touch it would be natural to pick a compound pose, but it also has different controls so you could leave thumbstick controlling brush size.

**Comment by fernandojsg** [comment] 2016-12-26 20:39
I agree that it could be confusing, in fact after playing with medium and quil I believe we should have a discussion about have different options on each hand by default instead of duplicating the same functionality on each hand as we do right now.

**Comment by avrljk** [comment] 2017-10-13 11:08
Duplicate of #214

**Closed** 2017-10-13 11:14 UTC
